# Site settings
title: siteTitle
email: none@example.com
description: >- 
  Write a short description of your site here.
baseurl: "" 
url: "http://yourdomain.com" 


theme: null
plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM


