
baseurl: "/SSG" 
url: "https://fflip0.github.io/SSG/" 


theme: null
plugins:
  - jekyll-feed
  - jekyll-toc

markdown: kramdown
kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
    values:
      toc: true
      toc_sticky: true


toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
